version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: python3.4 src/core/system_manager/init.py
    volumes:
    - ./:/usr/ichnosat
    ports:
     - "5000:5000"
     - "80:80"
     - "5001:5001"
     - "5002:5002"



