version: '2'
services:
  app:
    build: .
    command: sh /usr/ichnosat/src/system_manager/bash/init.sh
    volumes:
    - ./:/usr/ichnosat
    ports:
     - "5000:5000"
     - "80:80"
     - "5001:5001"
     - "5002:5002"



